In [2]:
from sympy import Matrix, Rational
import numpy as np

# Define the transition matrix using sympy with exact fractions
P = Matrix([
    [Rational(1),   Rational(0),   Rational(0),   Rational(0),   Rational(0)],
    [Rational(1,2), Rational(0),   Rational(1,2), Rational(0),   Rational(0)],
    [Rational(0),   Rational(1,2), Rational(0),   Rational(1,2), Rational(0)],
    [Rational(0),   Rational(0),   Rational(0), Rational(1,3),   Rational(2,3)],
    [Rational(0),   Rational(0),   Rational(0),   Rational(2,3), Rational(1,3)]
])

# Display the matrix
P


Matrix([
[  1,   0,   0,   0,   0],
[1/2,   0, 1/2,   0,   0],
[  0, 1/2,   0, 1/2,   0],
[  0,   0,   0, 1/3, 2/3],
[  0,   0,   0, 2/3, 1/3]])

In [88]:
P**2

Matrix([
[  1,   0,   0,   0,   0],
[1/2, 1/4,   0, 1/4,   0],
[1/4,   0, 1/4, 1/6, 1/3],
[  0,   0,   0, 5/9, 4/9],
[  0,   0,   0, 4/9, 5/9]])

In [89]:
P**3

Matrix([
[  1,   0,   0,     0,     0],
[5/8,   0, 1/8,  1/12,   1/6],
[1/4, 1/8,   0, 29/72,   2/9],
[  0,   0,   0, 13/27, 14/27],
[  0,   0,   0, 14/27, 13/27]])

In [90]:
P**4

Matrix([
[   1,    0,    0,      0,      0],
[ 5/8, 1/16,    0, 29/144,    1/9],
[5/16,    0, 1/16, 61/216, 37/108],
[   0,    0,    0,  41/81,  40/81],
[   0,    0,    0,  40/81,  41/81]])

In [91]:
P**5

Matrix([
[    1,    0,    0,        0,       0],
[21/32,    0, 1/32,   61/432,  37/216],
[ 5/16, 1/32,    0, 917/2592,  49/162],
[    0,    0,    0,  121/243, 122/243],
[    0,    0,    0,  122/243, 121/243]])

In [92]:
P**6

Matrix([
[    1,    0,    0,         0,         0],
[21/32, 1/64,    0,  917/5184,    49/324],
[21/64,    0, 1/64, 2485/7776, 1309/3888],
[    0,    0,    0,   365/729,   364/729],
[    0,    0,    0,   364/729,   365/729]])

In [93]:
P**7

Matrix([
[     1,     0,     0,           0,         0],
[85/128,     0, 1/128,  2485/15552, 1309/7776],
[ 21/64, 1/128,     0, 31613/93312, 1897/5832],
[     0,     0,     0,   1093/2187, 1094/2187],
[     0,     0,     0,   1094/2187, 1093/2187]])

In [103]:
# Define the transition matrix P using numpy arrays with rational numbers
P_np = np.array([
    [1,   0,   0,   0,   0],
    [1/2, 0,   1/2, 0,   0],
    [0,   1/2, 0,   1/2, 0],
    [0,   0,   0,  1/3,   2/3],
    [0,   0,   0,   2/3, 1/3]
], dtype=np.float64)

# Calculat # Ue P^n for a large n to approximate the limiting behavior
n = int(1e8)
P_np_n = np.linalg.matrix_power(P_np, n)

In [104]:
P_np_n

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.66666667, 0.        , 0.        , 0.16666667, 0.16666667],
       [0.33333333, 0.        , 0.        , 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.5       , 0.5       ],
       [0.        , 0.        , 0.        , 0.5       , 0.5       ]])

In [105]:
np.dot(np.array([0,0.5,0.5,0,0]), P_np_n)

array([0.5 , 0.  , 0.  , 0.25, 0.25])

In [110]:
Prw = np.array([
    [0,   0,   0,   1/2, 0,   1/2],
    [0,   0,   0,   0,   1/2, 1/2],
    [0,   0,   0,   1/2, 1/2, 0],
    [1/4, 0,   1/4, 0,   1/4, 1/4],
    [0,   1/4, 1/4, 1/4,  0, 1/4],
    [1/4, 1/4, 0,   1/4, 1/4, 0]
])

In [111]:
np.dot(np.array([1/6,1/6,1/6,1/6,1/6,1/6]), np.linalg.matrix_power(Prw, int(1e8)))

array([0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
       0.22222222])

In [112]:
np.linalg.matrix_power(Prw, int(1e8))

array([[0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
        0.22222222],
       [0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
        0.22222222],
       [0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
        0.22222222],
       [0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
        0.22222222],
       [0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
        0.22222222],
       [0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
        0.22222222]])

In [113]:
np.dot(np.array([1,0,0,0,0,0]), np.linalg.matrix_power(Prw, int(1e8)))

array([0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
       0.22222222])

In [114]:
import numpy as np

# Number of states in the Markov chain
n = Prw.shape[0]

# Create an augmented matrix (P.T - I)
A = Prw.T - np.eye(n)

# Add the normalization constraint as an additional row at the bottom
A = np.vstack([A, np.ones(n)])

# Create the augmented matrix for the right-hand side which is all zeros and a one for the normalization
b = np.zeros(n+1)
b[-1] = 1

# Solve the system using the least squares method since the system is overdetermined
pi, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

pi


array([0.11111111, 0.11111111, 0.11111111, 0.22222222, 0.22222222,
       0.22222222])

array([ 3.33333333e-01,  5.55111512e-17, -1.38777878e-16,  3.33333333e-01,
        3.33333333e-01])

In [11]:
# Define the transition matrix using sympy with exact fractions
P_3c = Matrix([
    [Rational(1),   Rational(0),   Rational(0),   Rational(0),   Rational(0), Rational(0),],
    [Rational(0),   Rational(1),   Rational(0),   Rational(0),   Rational(0), Rational(0),],
    [Rational(0),   Rational(0),   Rational(1),   Rational(0),   Rational(0), Rational(0),],
    [Rational(1,4),   Rational(0),   Rational(1,4),   Rational(0),   Rational(1,4), Rational(1,4),],
    [Rational(0),   Rational(1,4),   Rational(1,4),   Rational(0),   Rational(1,4), Rational(1,4),],
    [Rational(1,4),   Rational(1,4),   Rational(0),   Rational(1,4),   Rational(1,4), Rational(0),]
])

# Display the matrix
P_3c

Matrix([
[  1,   0,   0,   0,   0,   0],
[  0,   1,   0,   0,   0,   0],
[  0,   0,   1,   0,   0,   0],
[1/4,   0, 1/4,   0, 1/4, 1/4],
[  0, 1/4, 1/4,   0, 1/4, 1/4],
[1/4, 1/4,   0, 1/4, 1/4,   0]])

In [12]:
mu_0 = Matrix([
    [Rational(0), Rational(0), Rational(0), Rational(0), Rational(0), Rational(1),]
])
mu_0

Matrix([[0, 0, 0, 0, 0, 1]])

In [13]:
mu_0 * P_3c

Matrix([[1/4, 1/4, 0, 1/4, 1/4, 0]])